### ISSUE TITLE
[BUG] /cosmos/tx/v1beta1/txs/block/13214281 return error

### ISSUE THREAD

**Issue by Pzzzzzack** [classic-terra/core#265] opened 2023-06-16 10:54 UTC
**Describe the bug**
we use this api to get txs /cosmos/tx/v1beta1/txs/block/13214281. But it return this error

```
{
  "code": 3,
  "message": "unable to resolve type URL /terra.wasm.v1beta1.MsgExecuteContract: tx parse error: invalid request",
  "details": [
  ]
}
```
There are some MsgExecuteContract transactions in this block. It seems this api not support MsgExecuteContract transactions.

**To Reproduce**
call this api /cosmos/tx/v1beta1/txs/block/13214281

**Context & versions**
classic-core v2.1.1

**Comment by fragwuerdig** [comment] 2023-06-16 10:56
This is duplicate of #256. I will still let it open for you to comment on.

**Comment by Pzzzzzack** [comment] 2023-06-16 15:12
/cosmos/tx/v1beta1/txs/6937A6F688D0AEC9B4CC9F4E3D24B9F5CE40FCE45006F8550F124A89371AF5D0
this api return same error:
`{
  "code": 3,
  "message": "unable to resolve type URL /terra.wasm.v1beta1.MsgExecuteContract: tx parse error: invalid request",
  "details": [
  ]
}`
full http request is [https://terra-classic-lcd.publicnode.com/cosmos/tx/v1beta1/txs/6937A6F688D0AEC9B4CC9F4E3D24B9F5CE40FCE45006F8550F124A89371AF5D0](url)

**Closed** 2023-06-21 04:26 UTC
Labels: bug
